// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WCStatsTracker.Services;

#nullable disable

namespace WCStatsTracker.Migrations
{
    [DbContext(typeof(WCDBContext))]
    partial class WCDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("WCStatsTracker.Models.FlagSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FlagString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Flags");
                });

            modelBuilder.Entity("WCStatsTracker.Models.WCRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BossesKilled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharactersFound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChecksDone")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChestsOpened")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DidKTSkip")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DragonsKilled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EspersFound")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlagId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("RunLength")
                        .HasColumnType("TEXT");

                    b.Property<string>("Seed")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlagId");

                    b.ToTable("WCRuns");
                });

            modelBuilder.Entity("WCStatsTracker.Models.WCRun", b =>
                {
                    b.HasOne("WCStatsTracker.Models.FlagSet", "Flag")
                        .WithMany("Runs")
                        .HasForeignKey("FlagId");

                    b.Navigation("Flag");
                });

            modelBuilder.Entity("WCStatsTracker.Models.FlagSet", b =>
                {
                    b.Navigation("Runs");
                });
#pragma warning restore 612, 618
        }
    }
}
