// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WCStatsTracker.Services.DataAccess;

#nullable disable

namespace WCStatsTracker.Migrations
{
    [DbContext(typeof(WcDbContext))]
    partial class WcDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("AbilityWcRun", b =>
                {
                    b.Property<int>("AbilitiesAbilityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RunsWcRunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AbilitiesAbilityId", "RunsWcRunId");

                    b.HasIndex("RunsWcRunId");

                    b.ToTable("AbilityWcRun");
                });

            modelBuilder.Entity("CharacterWcRun", b =>
                {
                    b.Property<int>("CharactersCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RunsWcRunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharactersCharacterId", "RunsWcRunId");

                    b.HasIndex("RunsWcRunId");

                    b.ToTable("CharacterWcRun");
                });

            modelBuilder.Entity("WCStatsTracker.Models.Ability", b =>
                {
                    b.Property<int>("AbilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AbilityId");

                    b.ToTable("Abilities");

                    b.HasData(
                        new
                        {
                            AbilityId = 1,
                            Name = "Blitz"
                        },
                        new
                        {
                            AbilityId = 2,
                            Name = "Capture"
                        },
                        new
                        {
                            AbilityId = 3,
                            Name = "Control"
                        },
                        new
                        {
                            AbilityId = 4,
                            Name = "GP Rain"
                        },
                        new
                        {
                            AbilityId = 5,
                            Name = "Dance"
                        },
                        new
                        {
                            AbilityId = 6,
                            Name = "Health"
                        },
                        new
                        {
                            AbilityId = 7,
                            Name = "Jump"
                        },
                        new
                        {
                            AbilityId = 8,
                            Name = "Lore"
                        },
                        new
                        {
                            AbilityId = 9,
                            Name = "Morph"
                        },
                        new
                        {
                            AbilityId = 10,
                            Name = "Rage"
                        },
                        new
                        {
                            AbilityId = 11,
                            Name = "Runic"
                        },
                        new
                        {
                            AbilityId = 12,
                            Name = "Sketch"
                        },
                        new
                        {
                            AbilityId = 13,
                            Name = "Slot"
                        },
                        new
                        {
                            AbilityId = 14,
                            Name = "Steal"
                        },
                        new
                        {
                            AbilityId = 15,
                            Name = "SwdTech"
                        },
                        new
                        {
                            AbilityId = 16,
                            Name = "Throw"
                        },
                        new
                        {
                            AbilityId = 17,
                            Name = "Tools"
                        },
                        new
                        {
                            AbilityId = 18,
                            Name = "X Magic"
                        },
                        new
                        {
                            AbilityId = 19,
                            Name = "Shock"
                        },
                        new
                        {
                            AbilityId = 20,
                            Name = "MagiTek"
                        },
                        new
                        {
                            AbilityId = 21,
                            Name = "Possess"
                        });
                });

            modelBuilder.Entity("WCStatsTracker.Models.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            Name = "Terra"
                        },
                        new
                        {
                            CharacterId = 2,
                            Name = "Locke"
                        },
                        new
                        {
                            CharacterId = 3,
                            Name = "Cyan"
                        },
                        new
                        {
                            CharacterId = 4,
                            Name = "Shadow"
                        },
                        new
                        {
                            CharacterId = 5,
                            Name = "Edgar"
                        },
                        new
                        {
                            CharacterId = 6,
                            Name = "Sabin"
                        },
                        new
                        {
                            CharacterId = 7,
                            Name = "Celes"
                        },
                        new
                        {
                            CharacterId = 8,
                            Name = "Strage"
                        },
                        new
                        {
                            CharacterId = 9,
                            Name = "Relm"
                        },
                        new
                        {
                            CharacterId = 10,
                            Name = "Setzer"
                        },
                        new
                        {
                            CharacterId = 11,
                            Name = "Mog"
                        },
                        new
                        {
                            CharacterId = 12,
                            Name = "Gau"
                        },
                        new
                        {
                            CharacterId = 13,
                            Name = "Gogo"
                        },
                        new
                        {
                            CharacterId = 14,
                            Name = "Umaro"
                        });
                });

            modelBuilder.Entity("WCStatsTracker.Models.Flag", b =>
                {
                    b.Property<int>("FlagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FlagString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FlagId");

                    b.ToTable("Flags");
                });

            modelBuilder.Entity("WCStatsTracker.Models.WcRun", b =>
                {
                    b.Property<int>("WcRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BossesKilled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharactersFound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChecksDone")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChestsOpened")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateRan")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DidKTSkip")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DragonsKilled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EspersFound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlagId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("RunLength")
                        .HasColumnType("TEXT");

                    b.Property<string>("Seed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WcRunId");

                    b.HasIndex("FlagId");

                    b.ToTable("WCRuns");
                });

            modelBuilder.Entity("AbilityWcRun", b =>
                {
                    b.HasOne("WCStatsTracker.Models.Ability", null)
                        .WithMany()
                        .HasForeignKey("AbilitiesAbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WCStatsTracker.Models.WcRun", null)
                        .WithMany()
                        .HasForeignKey("RunsWcRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterWcRun", b =>
                {
                    b.HasOne("WCStatsTracker.Models.Character", null)
                        .WithMany()
                        .HasForeignKey("CharactersCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WCStatsTracker.Models.WcRun", null)
                        .WithMany()
                        .HasForeignKey("RunsWcRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WCStatsTracker.Models.WcRun", b =>
                {
                    b.HasOne("WCStatsTracker.Models.Flag", "Flag")
                        .WithMany("Runs")
                        .HasForeignKey("FlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flag");
                });

            modelBuilder.Entity("WCStatsTracker.Models.Flag", b =>
                {
                    b.Navigation("Runs");
                });
#pragma warning restore 612, 618
        }
    }
}
